steps:
- name: 'gcr.io/$PROJECT_ID/terraform'
  args: ['fmt']
- name: 'gcr.io/$PROJECT_ID/terraform'
  args: ['init']
- name: 'gcr.io/$PROJECT_ID/terraform'
  args: ['plan', '-out=plan.out']
- name: 'gcr.io/$PROJECT_ID/terraform'
  args: ['apply', 'plan.out']
